---
title: "Meta-analysis"
output: html_notebook
---

```{r setup, include=FALSE}
#open libarays
library(here)
library(metafor)
library(meta)
library(ggplot2)
library(dplyr)
library(plotly)
library(wesanderson)
library(LaCroixColoR)
library(readxl)

# all surveys combined
all <- read_excel("171122_dataset_greylit.xlsx") #all ages
```

```{r filter variables,echo = FALSE, warning = FALSE }
## all lifetime
all_LT<- all %>% 
  filter(timing == "lifetime") %>%
  filter(gender == "all") %>%
  mutate(prop = round(w.cases/total,3)*100)

## all current
all_current<- all %>% 
  filter(timing == "current") %>%
  filter(gender == "all") %>%
  mutate(prop = round(w.cases/total,3)*100) 

## all daily
all_daily<- all %>% 
  filter(timing == "daily") %>%
  filter(gender == "all") %>%
  mutate(prop = round(w.cases/total,3)*100) 
```

```{r meta-analysis_LT: all (region),echo = FALSE, warning = FALSE, fig.width = 10, fig.height=14}
# double arcsine transformation
ies.dat.all.LT <- escalc(xi = w.cases,
                  ni = total, 
                  data = all_LT, 
                  measure = "PFT")

b.all.LT <- metaprop(event = w.cases, 
            n = total, 
            studlab = country, 
            random = TRUE,
            sm = "PFT", 
            data = ies.dat.all.LT, 
            method = "Inverse", 
            method.tau = "DL", 
            digits = 3,
            subgroup = region,
            subgroup.name = "WHO Region")
b.all.LT

forest(b.all.LT,
       col.by = "black",
       leftcols = c("studlab","author_year", "cohort_abv", "year", "event","n"),
       leftlabs = c("WHO Region and country", "Author (year of publication)", "Cohort", "Data collection (year)", "Lifetime use (n)", "Total participants (n)"),
       rightcols = c("effect", "ci", "age_range", "resentativeness"),
       rightlabs = c("Prevalence", "95% C.I.", "Age, years (range)", "Representativeness"),
       xlab = "Prevalence of Lifetime HTP Use", smlab = "", 
       xlim = c(0,20),
       pscale = 100,
       weight.study = "random", squaresize = 0.5, 
       fixed = FALSE,
       digits = 2,
       transf= transf.ipft.hm)
```


##LIFETIME USE PLOT
```{r plot by region over year for lifetime,echo = FALSE, warning = FALSE,fig.width = 12, fig.height=4 }
#use this dataset to plot 
group_all_LT<- all_current %>% 
  filter(timing == "current") %>%
  filter(gender == "all") %>%
  filter(region == "European Region" | region == "Region of the Americas" | region == "African Region") %>%
  mutate(prop = round(w.cases/total,3)*100)

p<- ggplot(group_all_LT, aes(x = factor(year), y = prop)) +
  geom_point(aes(color = region, shape = region, alpha=0.5), size = 3) +
  scale_colour_manual(values = c("#EE0099","#0000AC", "#BB3099")) +
  scale_fill_manual(values = c("#EE0099","#0000AC", "#BB3099")) +
  xlab("Survey Year") +
  ylab("Weighted Lifetime Use %") +
  scale_y_continuous(limits = c(0, 15)) + 
  theme(axis.text.x = element_text(angle = 22)) +
  theme(legend.title = element_blank()) +
  theme(axis.text=element_text(size=8),text = element_text(size=12))+
  theme(legend.position = "none") +
  facet_wrap(~ region)
ggplotly(p)
```